// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Counter(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* count */state[/* count */0] + 1 | 0];
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  var countMsg = "Count: " + String(match[0][/* count */0]);
  return React.createElement("div", undefined, React.createElement("p", undefined, countMsg), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Add */0);
                    })
                }, "Add"));
}

var make = Counter;

var $$default = Counter;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
