// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Header = require("../components/Header.bs.js");
var Counter = require("../components/Counter.bs.js");

function About(Props) {
  return React.createElement("div", undefined, React.createElement(Header.make, { }), React.createElement("p", undefined, "This is the about page."), React.createElement(Counter.make, { }));
}

var make = About;

var $$default = About;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
