// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Header = require("../components/Header.bs.js");
var Counter = require("../components/Counter.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function Index(Props) {
  var onServer = Props.onServer;
  return React.createElement("div", undefined, React.createElement(Header.make, { }), React.createElement("p", undefined, "HOME PAGE is here!"), React.createElement("p", undefined, "onServer: " + Pervasives.string_of_bool(onServer)), React.createElement(Counter.make, { }));
}

function getInitialProps(context) {
  var match = context.req;
  return {
          onServer: !(match == null)
        };
}

var inject = ( (cls, fn) => cls.getInitialProps = fn );

Curry._2(inject, Index, getInitialProps);

var make = Index;

var $$default = Index;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getInitialProps = getInitialProps;
exports.inject = inject;
/* inject Not a pure module */
